export const actionTypes = {
  // user
  REGISTER: 'REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGINOUT: 'USER_LOGINOUT',
  GET_USERINFO: 'GET_USERINFO',
  // article
  GET_ARTICLE: 'GET_ARTICLE',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  // todolist
  GET_TODOLIST: 'GET_TODOLIST',
  ADD_TODOLIST: 'ADD_TODOLIST',
  UPDATE_TODOLIST: 'UPDATE_TODOLIST',
  DEL_TODOLIST: 'DEL_TODOLIST',
}
